// Automatically generated by astro-icon
// ba910b7ddb423e9b3aa0ae6526501298ce623befc834ce4ea61d181a39f2c0dd

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-left"
		| "arrow-right"
		| "facebook(24x24)"
		| "instagram(24x24)"
		| "KRBsvg"
		| "linkedin(24x24)"
		| "x2";
}